### ISSUE TITLE
What do you mean by "Unbiasable" here?

### ISSUE THREAD

**Issue by HoOngEe** [dgamingfoundation/tendermint#106]
I found a comment "many random beacons used for consensus are slightly biasable; what's fine for cryptographic sortition is not fine for a game of blackjack" in [Arcade specification](https://github.com/corestario/tendermint/blob/develop/docs/arcade/arcade.md). I understood the meaning of "biased" here like the following: Even if one conduct samplings a lot of times, the distribution result does not converge to the mathematical one. In that sense, does the "BLS-based random beacon is unbiased" means your implementation converges well to the mathematically ideal distribution as long as the keys are generated from the DKG?

**Comment by HoOngEe** [comment]
I tried to find a proper communication medium but I failed to find it.

**Comment by SK0M0R0H** [comment]
Hi,
 
We use "unbiasability" property in terms of randomness beacon. It means that any party (or set of colluding parties with size <= t) is not able to change the protocol output to their advantage. So unbiasability and unpredictability properties together provide the uniform distribution regardless of the adversary actions (if required assumptions are met) and the adversary can't flip even the bit of the output. 
You can find other examples of "unbiasability"/"bias-resistance" definition in these papers: 
https://eprint.iacr.org/2019/1320
https://eprint.iacr.org/2018/319
https://eprint.iacr.org/2016/1067

We are going to explain it cleaner in the white paper.

**Comment by vshvsh** [comment]
> I tried to find a proper communication medium but I failed to find it.

Added a public e-mail to our github page; alternatively, it's available on our web page.

**Comment by HoOngEe** [comment]
Thank you for the response
