### ISSUE TITLE
Can't get dependency cosmos-utils

### ISSUE THREAD

**Issue by HaoyangLiu** [dgamingfoundation/tendermint#112]
The go mod file specified dependency on cosmos-utils
https://github.com/corestario/tendermint/blob/8650b9690967deae17a8425039bfaf29fe575445/go.mod#L40

But I can't access `github.com/corestario/cosmos-utils`. Is this a private repository?

**Comment by vshvsh** [comment]
It was, fixed now. Thank you for the heads up.
